# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule: Every Hour.
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
    push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.17
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Nate-Wilkins
          template: classic
          base: ""
          config_timezone: America/New_York
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, review, wiki, star, release, member, comment
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_activity_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot], allcontributors[bot]
